import {createContext,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {Play,Pause,SkipBack,SkipForward,X,Music2,ListMusic,Shuffle,Repeat,SlidersHorizontal,Volume2,VolumeX,ChevronDown,ChevronUp,Trash2} from 'lucide-react';
import {api,duration,thumbnailUrl,type FileEntry} from './api';
export function musicTags(f:FileEntry){const t:Record<string,string>={};try{for(const[k,v]of Object.entries(JSON.parse(f.metadata||'{}')))t[k.toLowerCase()]=String(v);}catch{}return {title:t.title||f.name,artist:t.artist||'Неизвестный исполнитель',album:t.album||'Без альбома',cover:!!t.cover,missing:!t.title||!t.artist};}
type RepeatMode='off'|'all'|'one';
type Session={queue:FileEntry[];index:number;time:number;volume:number;muted:boolean;repeat:RepeatMode;compact:boolean};
const KEY='lc-music-session-v1';
function restore():Session{const empty:Session={queue:[],index:0,time:0,volume:0.8,muted:false,repeat:'off',compact:false};try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(!s)return empty;const queue=Array.isArray(s.queue)?s.queue.filter((f:FileEntry)=>f&&typeof f.id==='string'&&/^[a-f0-9]{32}$/i.test(f.id)&&f.kind==='audio').slice(0,1000):[];return {queue,index:Math.max(0,Math.min(queue.length-1,Number(s.index)||0)),time:Math.max(0,Number(s.time)||0),volume:Math.max(0,Math.min(1,Number.isFinite(s.volume)?s.volume:0.8)),muted:!!s.muted,repeat:['off','all','one'].includes(s.repeat)?s.repeat:'off',compact:!!s.compact};}catch{return empty;}}
type Controls=Omit<Session,'time'>&{playing:boolean;error:string;play:(q:FileEntry[],i:number)=>void;toggle:()=>void;seek:(n:number)=>void;next:(n:number)=>void;close:()=>void;shuffle:()=>void;remove:(i:number)=>void;setRepeat:(r:RepeatMode)=>void;setVolume:(v:number)=>void;setMuted:(v:boolean)=>void;setCompact:(v:boolean)=>void};
const Context=createContext<Controls|null>(null),Progress=createContext({time:0,total:0});
export function useMusic(){return useContext(Context)!;}
export function MusicProvider({children}:{children:ReactNode}){
 const [initial]=useState(restore),[queue,setQueue]=useState(initial.queue),[index,setIndex]=useState(initial.index),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[repeat,setRepeat]=useState(initial.repeat),[volume,setVolume]=useState(initial.volume),[muted,setMuted]=useState(initial.muted),[compact,setCompact]=useState(initial.compact),[time,setTime]=useState(initial.time),[total,setTotal]=useState(0);
 const audio=useRef<HTMLAudioElement>(null),autoplay=useRef(false),resumeAt=useRef(initial.time),lastSave=useRef(0),state=useRef({queue,index,repeat,volume,muted,compact});state.current={queue,index,repeat,volume,muted,compact};const current=queue[index];
 const actions=useMemo(()=>{
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({...state.current,time:audio.current?.currentTime||resumeAt.current||0}));}catch{}};
  const seek=(n:number)=>{const a=audio.current;if(a&&Number.isFinite(n)){a.currentTime=Math.max(0,Math.min(a.duration||n,n));setTime(a.currentTime);save();}};
  const start=()=>void audio.current?.play().catch(()=>setError('Нажмите воспроизведение, чтобы продолжить. Если файл удалён, выберите другой трек.'));
  const play=(q:FileEntry[],i:number)=>{if(!q[i])return;setError('');if(state.current.queue[state.current.index]?.id===q[i].id){setQueue(q);setIndex(i);start();return;}resumeAt.current=0;autoplay.current=true;setQueue(q);setIndex(i);};
  const next=(n:number)=>{const s=state.current;if(!s.queue.length)return;const i=(s.index+n+s.queue.length)%s.queue.length;if(i===s.index){seek(0);start();}else play(s.queue,i);};
  const toggle=()=>{if(audio.current?.paused)start();else audio.current?.pause();};
  const close=()=>{audio.current?.pause();autoplay.current=false;resumeAt.current=0;setQueue([]);setIndex(0);setTime(0);setError('');};
  const shuffle=()=>{const s=state.current,f=s.queue[s.index];if(!f)return;const others=s.queue.filter(t=>t.id!==f.id);for(let i=others.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[others[i],others[j]]=[others[j],others[i]];}setQueue([f,...others]);setIndex(0);};
  const remove=(i:number)=>{const s=state.current;if(s.queue.length===1){close();return;}const q=s.queue.filter((_,k)=>k!==i);if(i===s.index){resumeAt.current=0;autoplay.current=!audio.current?.paused;}setQueue(q);setIndex(i<s.index?s.index-1:Math.min(s.index,q.length-1));};
  return {save,seek,play,next,toggle,close,shuffle,remove};
 },[]);
 useEffect(()=>{if(audio.current){audio.current.volume=volume;audio.current.muted=muted;}},[volume,muted]);
 useEffect(()=>actions.save(),[queue,index,volume,muted,repeat,compact,actions]);
 useEffect(()=>{const save=()=>actions.save();window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',save);return()=>{window.removeEventListener('pagehide',save);document.removeEventListener('visibilitychange',save);};},[actions]);
 useEffect(()=>{setTotal(current?.duration||0);setTime(resumeAt.current);setError('');if(current&&autoplay.current){autoplay.current=false;void audio.current?.play().catch(()=>setError('Нажмите воспроизведение, чтобы продолжить.'));}},[current?.id]);
 useEffect(()=>{const refresh=()=>{const f=state.current.queue[state.current.index];if(f)void api<FileEntry>('/files/'+f.id).then(f=>setQueue(q=>q.map(t=>t.id===f.id?f:t))).catch(()=>{});};window.addEventListener('lc-track-changed',refresh);return()=>window.removeEventListener('lc-track-changed',refresh);},[]);
 useEffect(()=>{if(!('mediaSession'in navigator))return;if(!current){navigator.mediaSession.metadata=null;return;}const t=musicTags(current);navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:t.album,artwork:t.cover?[{src:location.origin+thumbnailUrl(current,512),sizes:'512x512',type:'image/jpeg'}]:[]});navigator.mediaSession.setActionHandler('play',()=>void audio.current?.play().catch(()=>{}));navigator.mediaSession.setActionHandler('pause',()=>audio.current?.pause());navigator.mediaSession.setActionHandler('previoustrack',()=>actions.next(-1));navigator.mediaSession.setActionHandler('nexttrack',()=>actions.next(1));navigator.mediaSession.setActionHandler('seekto',d=>actions.seek(d.seekTime||0));},[current?.id,current?.metadata,actions]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!state.current.queue.length||e.defaultPrevented||e.ctrlKey||e.metaKey||(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,button,[contenteditable],[role=dialog]'))||document.querySelector('.viewer'))return;if(e.code==='Space'){e.preventDefault();actions.toggle();}else if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();actions.next(1);}else if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();actions.next(-1);}else if(e.key.toLowerCase()==='m')setMuted(v=>!v);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[actions]);
 const controls=useMemo<Controls>(()=>({queue,index,playing,error,repeat,volume,muted,compact,...actions,setRepeat,setVolume,setMuted,setCompact}),[queue,index,playing,error,repeat,volume,muted,compact,actions]);
 return <Context.Provider value={controls}><Progress.Provider value={{time,total}}>{children}<audio ref={audio} src={current?'/api/files/'+current.id+'/original':undefined} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);actions.save();}} onTimeUpdate={()=>{setTime(audio.current?.currentTime||0);if(Date.now()-lastSave.current>5000){actions.save();lastSave.current=Date.now();}}} onLoadedMetadata={()=>{const a=audio.current;if(a&&Number.isFinite(a.duration)){setTotal(a.duration);if(resumeAt.current){a.currentTime=Math.min(resumeAt.current,Math.max(0,a.duration-0.1));resumeAt.current=0;setTime(a.currentTime);}}}} onEnded={()=>{if(repeat==='one'){actions.seek(0);void audio.current?.play().catch(()=>{});}else if(index<queue.length-1||repeat==='all')actions.next(1);else{setPlaying(false);actions.save();}}} onError={()=>{if(current){setPlaying(false);setError('Не удалось открыть трек. Проверьте файл и подключение к серверу.');}}}/></Progress.Provider></Context.Provider>;
}
function MusicProgress(){const m=useMusic(),p=useContext(Progress);return <div className="mini-progress"><input type="range" aria-label="Позиция музыки" min={0} max={p.total||1} step={0.1} value={Math.min(p.time,p.total||1)} onChange={e=>m.seek(Number(e.target.value))}/><small>{duration(p.time)} / {duration(p.total)}</small></div>;}
export function MiniPlayer({onEdit}:{onEdit:(f:FileEntry)=>void}){const m=useMusic(),[open,setOpen]=useState(false),f=m.queue[m.index];if(!f)return null;const t=musicTags(f);return <><div className={'mini-player '+(m.compact?'compact':'')} role="region" aria-label="Музыкальный плеер"><div className="mini-cover">{t.cover?<img src={thumbnailUrl(f,256)} alt=""/>:<Music2 size={24}/>}</div><div className="mini-title"><strong>{t.title}</strong><small>{m.error||t.artist}</small></div><div className="mini-actions"><button aria-label="Предыдущая запись" title="Alt + ←" onClick={()=>m.next(-1)}><SkipBack size={20}/></button><button aria-label={m.playing?'Пауза музыки':'Воспроизвести музыку'} title="Пробел" onClick={m.toggle}>{m.playing?<Pause size={23}/>:<Play size={23}/>}</button><button aria-label="Следующая запись" title="Alt + →" onClick={()=>m.next(1)}><SkipForward size={20}/></button></div>{!m.compact&&<MusicProgress/>}<div className="mini-volume"><button aria-label={m.muted?'Включить звук':'Отключить звук'} onClick={()=>m.setMuted(!m.muted)}>{m.muted||m.volume===0?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><input type="range" aria-label="Громкость музыки" min={0} max={1} step={0.01} value={m.volume} onChange={e=>{m.setVolume(Number(e.target.value));m.setMuted(false);}}/><small>{Math.round(m.volume*100)}%</small></div>{!m.compact&&<button aria-label="Редактировать текущий трек" onClick={()=>onEdit(f)}><SlidersHorizontal size={19}/></button>}<button aria-label="Очередь воспроизведения" onClick={()=>setOpen(!open)}><ListMusic size={21}/></button><button aria-label={m.compact?'Развернуть плеер':'Свернуть плеер'} onClick={()=>m.setCompact(!m.compact)}>{m.compact?<ChevronUp size={19}/>:<ChevronDown size={19}/>}</button><button aria-label="Закрыть музыкальный плеер" onClick={m.close}><X size={19}/></button></div>{open&&<div className="music-queue"><div className="dialog-head"><h3>Очередь · {m.queue.length}</h3><button onClick={m.shuffle} aria-label="Перемешать очередь"><Shuffle size={18}/></button><button className={m.repeat!=='off'?'chosen':''} aria-label={'Режим повтора: '+(m.repeat==='off'?'выключен':m.repeat==='all'?'вся очередь':'одна запись')} onClick={()=>m.setRepeat(m.repeat==='off'?'all':m.repeat==='all'?'one':'off')}><Repeat size={18}/>{m.repeat==='one'&&<small>1</small>}</button><button onClick={()=>setOpen(false)} aria-label="Закрыть очередь"><X size={18}/></button></div><p className="quiet-note">Пробел — пауза · Alt + ← / → — трек · M — звук</p>{m.queue.map((f,i)=><div className="queue-row" key={f.id}><button className={'music-queue-track '+(i===m.index?'chosen':'')} onClick={()=>m.play(m.queue,i)}><span>{i+1}</span><div>{musicTags(f).title}<small>{musicTags(f).artist}</small></div><small>{duration(f.duration||0)}</small></button><button aria-label={'Убрать из очереди: '+musicTags(f).title} onClick={()=>m.remove(i)}><Trash2 size={16}/></button></div>)}</div>}</>;}
