<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/LocalCloud.Infrastructure/LocalCloud.Infrastructure.csproj"/><ProjectReference Include="../../src/LocalCloud.Updater/LocalCloud.Updater.csproj" /></ItemGroup></Project>
