import {chromium,expect} from '../src/LocalCloud.Web/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'),base=process.env.LOCALCLOUD_TEST_URL,f=JSON.parse(fs.readFileSync(process.env.LOCALCLOUD_FIXTURES));
const browser=await chromium.launch({executablePath:process.env.LOCALCLOUD_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const screenshots=root+'/artifacts/screenshots/1.3';fs.mkdirSync(screenshots,{recursive:true});
async function view(name){await page.getByRole('button',{name,exact:true}).first().click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();}
await page.goto(base);await expect(page.getByRole('heading',{name:'Фото',exact:true})).toBeVisible();
await expect(page.locator('.sidebar nav small')).toBeVisible();const fonts=await page.evaluate(()=>[...document.querySelectorAll('.sidebar *')].filter(e=>e.children.length===0&&e.textContent.trim()).map(e=>({text:e.textContent.trim(),size:getComputedStyle(e).fontSize})));
expect(fonts.map(v=>v.size)).toEqual(JSON.parse(fs.readFileSync(root+'/artifacts/baseline13-fonts.json')).map(v=>v.size));checks.push('sidebar fonts unchanged from real 1.2');
await page.locator('.file-open').first().click();await expect(page.locator('.photo-canvas')).toBeVisible();await page.locator('.photo-canvas').dblclick();await expect.poll(()=>page.locator('.photo-canvas img').evaluate(e=>e.style.transform)).toContain('scale(2.5)');
const box=await page.locator('.photo-canvas').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+30);await page.mouse.up();expect(await page.locator('.photo-canvas img').evaluate(e=>e.style.transform)).not.toContain('translate3d(0px, 0px');
await page.locator('.photo-canvas').dblclick();await page.getByRole('button',{name:'Информация',exact:true}).click();await page.screenshot({path:screenshots+'/photo-information.png'});await page.getByRole('button',{name:'Информация',exact:true}).click();await page.getByRole('button',{name:'Редактировать фото',exact:true}).click();await expect(page.locator('.photo-edit-panel')).toBeVisible();await page.screenshot({path:screenshots+'/photo-editor.png'});await page.setViewportSize({width:390,height:844});const stage=await page.locator('.viewer-stage').boundingBox();expect(stage.height).toBeGreaterThan(160);expect(stage.y).toBeGreaterThanOrEqual(65);await page.screenshot({path:screenshots+'/photo-editor-mobile.png'});await page.getByRole('button',{name:'Редактировать фото',exact:true}).click();const touch=await page.context().newCDPSession(page);const b=await page.locator('.photo-canvas').boundingBox(),y=b.y+b.height/2,x=b.x+b.width/2;await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-45,y},{x:x+45,y}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-100,y},{x:x+100,y}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>page.locator('.photo-canvas img').evaluate(e=>e.style.transform)).not.toContain('scale(1)');await touch.detach();await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});checks.push('photo double zoom pan mobile pinch metadata and editor');
await view('Файлы');await page.getByRole('button',{name:'Музыка',exact:true}).click();await expect(page.getByRole('heading',{name:'Музыка',exact:true})).toBeVisible();await page.getByRole('button',{name:'Открыть Русская песня.mp3',exact:true}).click();await expect(page.locator('.mini-player')).toBeVisible();await expect.poll(()=>page.locator('audio').evaluate(e=>e.currentTime)).toBeGreaterThan(.1);const start=await page.locator('audio').evaluate(e=>e.currentTime);
await view('Настройки');await expect.poll(()=>page.locator('audio').evaluate(e=>e.currentTime)).toBeGreaterThan(start);await page.getByRole('button',{name:'Очередь воспроизведения'}).click();await expect(page.locator('.music-queue-track')).toHaveCount(4);await page.getByRole('button',{name:'Режим повтора: выключен'}).click();await page.getByRole('button',{name:'Режим повтора: вся очередь'}).click();await expect(page.getByRole('button',{name:'Режим повтора: одна запись'})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Перемешать очередь'}).click();await page.getByRole('button',{name:'Закрыть очередь',exact:true}).click();
await page.getByRole('button',{name:'Редактировать текущий трек'}).click();await expect(page.getByRole('dialog',{name:'Редактировать трек'})).toBeVisible();await page.getByLabel('Название',{exact:true}).fill('Русская песня исправлена');await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.locator('.mini-title strong')).toHaveText('Русская песня исправлена');await page.screenshot({path:screenshots+'/music-desktop.png'});checks.push('music persists navigation repeat shuffle live tag editing');
for(const width of [375,390,430,768,1024,1440,1920]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const bounds=await page.locator('.mini-player').boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(width+1);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:screenshots+'/music-mobile.png'});await page.getByRole('button',{name:'Закрыть музыкальный плеер'}).click();await page.setViewportSize({width:1440,height:1000});
await page.getByRole('button',{name:'Тёмная',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:screenshots+'/settings-dark.png',fullPage:true});await page.getByRole('button',{name:'Светлая',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');checks.push('themes and 375 390 430 768 1024 1440 1920 no horizontal overflow');
await page.getByRole('button',{name:'История загрузок',exact:true}).click();await expect(page.getByRole('dialog',{name:'История загрузок'})).toBeVisible();await expect(page.getByText(/Дубликат пропущен/)).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.overlay')).toHaveCount(0);checks.push('real upload history shows duplicate result');
await view('Файлы');await page.getByRole('button',{name:'Files Папка на компьютере',exact:true}).click();await page.getByRole('button',{name:'Документы Папка на компьютере',exact:true}).click();await page.getByRole('button',{name:'Открыть Документ.pdf',exact:true}).click();await expect(page.locator('.pdf-page canvas')).toBeVisible();await expect.poll(()=>page.locator('.pdf-page canvas').evaluate(e=>e.width)).toBeGreaterThan(100);await page.getByLabel('Текстовая пометка').fill('Привет, Илья');await page.getByRole('button',{name:'Разместить текст'}).click();await page.locator('.pdf-page canvas').click({position:{x:100,y:100}});await expect(page.locator('.pdf-note')).toHaveText('Привет, Илья');await page.getByRole('button',{name:'Сохранить копию',exact:true}).click();await expect(page.getByText('Копия добавлена в очередь загрузок. Оригинал сохранён.')).toBeVisible();await expect.poll(async()=>((await (await page.request.get(base+'/api/files?view=all&search=Документ-edited.pdf')).json()).total)).toBe(1);await page.screenshot({path:screenshots+'/pdf-editor.png'});await page.keyboard.press('Escape');if(await page.getByRole('button',{name:'Свернуть загрузки'}).isVisible())await page.getByRole('button',{name:'Свернуть загрузки'}).click();checks.push('PDF renderer and Cyrillic annotation upload copy');
// Upload more than five confirmed chunks with an interrupted PATCH and exact resulting bytes.
await page.getByRole('button',{name:'Загрузить',exact:true}).click();await page.getByRole('dialog').getByRole('combobox').selectOption('Files');const content=crypto.randomBytes(40*1024*1024+117);let patches=0;
await page.route('**/uploads/*',async route=>{if(route.request().method()==='PATCH'&&++patches===2){await route.abort('connectionreset');return;}await route.continue();});
await page.locator('input[type=file]:not([webkitdirectory])').setInputFiles({name:'Release13-multi-chunk.bin',mimeType:'application/octet-stream',buffer:content});await expect.poll(async()=>((await (await page.request.get(base+'/api/files?view=all&search=Release13-multi-chunk.bin')).json()).total),{timeout:90000}).toBe(1);expect(patches).toBeGreaterThan(5);
const uploaded=await (await page.request.get(base+'/api/files?view=all&search=Release13-multi-chunk.bin')).json(),data=await (await page.request.get(base+'/api/files/'+uploaded.items[0].id+'/original')).body();expect(crypto.createHash('sha256').update(data).digest('hex')).toBe(crypto.createHash('sha256').update(content).digest('hex'));await page.unroute('**/uploads/*');checks.push('40MiB resumable upload recovers disconnect exact hash');

// File-system folder import preserves relative nesting through the same tus finalization.
if(await page.getByRole('button',{name:'Свернуть загрузки'}).isVisible())await page.getByRole('button',{name:'Свернуть загрузки'}).click();await page.getByRole('button',{name:'Загрузить',exact:true}).click();await page.getByRole('dialog').getByRole('combobox').selectOption('Files');const directory=fs.mkdtempSync('/tmp/localcloud-ui-import-');fs.mkdirSync(directory+'/Nested');fs.writeFileSync(directory+'/one.txt','USB folder import');fs.writeFileSync(directory+'/Nested/two.txt','nested exact bytes');await page.locator('input[webkitdirectory]').setInputFiles(directory);await expect.poll(async()=>((await (await page.request.get(base+'/api/files?view=all&search='+encodeURIComponent(path.basename(directory)+'/Nested/two.txt'))).json()).total)).toBe(1);checks.push('folder import preserves nested physical paths');

const guest=await browser.newPage({viewport:{width:390,height:844}});guest.on('pageerror',e=>errors.push(e.message));await guest.goto(base+f.share);await expect(guest.getByRole('heading',{name:'Наши фото',exact:true})).toBeVisible();await guest.locator('.shared-file').first().click();await expect(guest.locator('.shared-viewer')).toBeVisible();await guest.screenshot({path:screenshots+'/shared-mobile.png'});expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();checks.push('scoped guest folder mobile interface');
await browser.close();expect(errors).toEqual([]);const result={checks,errors,multiChunkBytes:content.length,patchRequests:patches};fs.writeFileSync(root+'/docs/release13-ui-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
