import {chromium as playwright,expect} from '../src/LocalCloud.Web/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import os from 'node:os';import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'..'),workspace=path.resolve(root,'../..');const chromiumPath=process.env.LOCALCLOUD_CHROMIUM;
const data=fs.mkdtempSync(path.join(os.tmpdir(),'localcloud-ui14-')),lib=data+'/library';fs.mkdirSync(lib,{recursive:true});fs.cpSync(root+'/artifacts/test14/library',lib,{recursive:true});fs.rmSync(lib+'/.localcloud',{recursive:true,force:true});fs.writeFileSync(data+'/settings.json',JSON.stringify({StorageRoot:lib,Port:43146,AllowLan:true,LaunchAtStartup:false}));
fs.cpSync(root+'/src/LocalCloud.Server/wwwroot',root+'/src/LocalCloud.Server/bin/Release/net10.0/wwwroot',{recursive:true});
const log=fs.openSync(data+'/server.log','w'),server=spawn(process.env.LOCALCLOUD_DOTNET||workspace+'/runtime/dotnet/dotnet',[root+'/src/LocalCloud.Server/bin/Release/net10.0/LocalCloud.Server.dll'],{env:{...process.env,LOCALCLOUD_CONFIG:data+'/settings.json'},stdio:['ignore',log,log]});
let browser;const checks=[],errors=[];const base='http://localhost:43146';
try{
 await new Promise(r=>setTimeout(r,1200));
 browser=await playwright.launch({executablePath:chromiumPath,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--single-process','--no-zygote'],headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByRole('button',{name:'Музыка',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Музыка',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Слушать список',exact:true}).click();await expect(page.locator('.mini-player')).toBeVisible();await expect.poll(()=>page.locator('audio').evaluate(a=>a.paused)).toBe(false);
 await page.getByLabel('Громкость музыки').fill('0.35');await expect.poll(()=>page.locator('audio').evaluate(a=>a.volume)).toBe(.35);await page.getByRole('button',{name:'Отключить звук',exact:true}).click();await expect.poll(()=>page.locator('audio').evaluate(a=>a.muted)).toBe(true);await page.getByRole('button',{name:'Включить звук',exact:true}).click();checks.push('volume and mute applied to audio');
 await page.getByRole('button',{name:/^Фото/}).first().click();await expect.poll(()=>page.locator('audio').evaluate(a=>a.currentTime)).toBeGreaterThan(0);
 await page.request.post(base+'/api/background',{data:{paused:true}});await page.waitForTimeout(1800);await page.evaluate(()=>{window.galleryMutations=0;new MutationObserver(()=>window.galleryMutations++).observe(document.querySelector('.main'),{childList:true,subtree:true,characterData:true,attributes:true});});await page.waitForTimeout(1400);expect(await page.evaluate(()=>window.galleryMutations)).toBe(0);checks.push('music ticks do not mutate gallery');
 await page.getByLabel('Позиция музыки').fill('12');await page.getByRole('button',{name:'Свернуть плеер',exact:true}).click();await page.reload();await expect(page.locator('.mini-player.compact')).toBeVisible();await expect.poll(()=>page.locator('audio').evaluate(a=>a.readyState)).toBeGreaterThan(0);expect(await page.locator('audio').evaluate(a=>a.paused)).toBe(true);expect(await page.locator('audio').evaluate(a=>a.volume)).toBe(.35);expect(await page.locator('audio').evaluate(a=>a.currentTime)).toBeGreaterThan(11);checks.push('session restores queue position volume and compact mode without autoplay');
 await page.locator('h1').click();await page.keyboard.press('Space');await expect.poll(()=>page.locator('audio').evaluate(a=>a.paused)).toBe(false);await page.keyboard.press('Space');await expect.poll(()=>page.locator('audio').evaluate(a=>a.paused)).toBe(true);checks.push('keyboard play and pause');await page.getByRole('button',{name:'Развернуть плеер'}).click();await page.getByRole('button',{name:'Очередь воспроизведения'}).click();await expect(page.locator('.music-queue-track')).toHaveCount(2);await page.getByRole('button',{name:'Режим повтора: выключен'}).click();await page.getByRole('button',{name:'Режим повтора: вся очередь'}).click();await expect(page.getByRole('button',{name:'Режим повтора: одна запись'})).toBeVisible();await page.getByRole('button',{name:'Закрыть очередь',exact:true}).click();checks.push('queue and repeat controls');
 await page.getByRole('button',{name:'Музыка',exact:true}).first().click();await page.getByLabel('Без названия или исполнителя').check();await expect(page.getByRole('button',{name:'Открыть Без-тегов.mp3',exact:true})).toBeVisible();await page.getByLabel('Без названия или исполнителя').uncheck();await page.getByLabel('Сортировка').selectOption('artist');checks.push('music sort and missing tags filter');
 await page.getByRole('button',{name:'Редактировать текущий трек'}).click();await expect(page.getByRole('button',{name:'Предпросмотр записи в MP3'})).toBeVisible();await page.getByRole('button',{name:'Предпросмотр записи в MP3'}).click();await expect(page.locator('.tag-write-preview')).toBeVisible();await page.keyboard.press('Escape');checks.push('MP3 confirmation preview');
 const shots=root+'/docs/screenshots/1.4';fs.mkdirSync(shots,{recursive:true});for(const width of[375,390,430,768,1024,1440,1920]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const bounds=await page.locator('.mini-player').boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(width+1);await page.screenshot({path:shots+'/music-'+width+'.png'});}checks.push('music layout at seven viewport widths');
 await page.setViewportSize({width:1440,height:1000});await page.request.post(base+'/api/background',{data:{paused:false}});await page.getByRole('button',{name:'Инструменты',exact:true}).click();await expect(page.getByRole('heading',{name:'Нагрузка и фоновые задачи'})).toBeVisible();await expect(page.getByText('CPU сервера',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Приостановить фоновые задачи'}).click();await expect(page.getByRole('button',{name:'Продолжить обработку'})).toBeVisible();await page.screenshot({path:shots+'/tools.png'});await page.keyboard.press('Escape');checks.push('tools direct navigation diagnostics and pause');
 await page.getByRole('button',{name:'Загрузки',exact:true}).first().click();await expect(page.getByRole('dialog',{name:'История загрузок'})).toBeVisible();await page.keyboard.press('Escape');checks.push('downloads direct navigation');
 expect(errors).toEqual([]);fs.writeFileSync(root+'/docs/release14-ui-result.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));
}finally{if(browser)await browser.close();server.kill('SIGTERM');fs.closeSync(log);}
