import {chromium,expect} from '../src/LocalCloud.Web/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');const screenshots=path.join(root,'artifacts/screenshots');fs.mkdirSync(screenshots,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.LOCALCLOUD_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const failures=[];const consoleErrors=[];const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>consoleErrors.push(e.message));
const base=process.env.LOCALCLOUD_TEST_URL||'http://localhost:43110';
await page.goto(base);await expect(page.getByRole('heading',{name:'Фото',exact:true})).toBeVisible();await expect(page.locator('.file-card').first()).toBeVisible();
await page.screenshot({animations:'disabled',path:path.join(screenshots,'desktop-light.png'),fullPage:true});
await page.getByRole('button',{name:'Открыть IMG_1201.jpg',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Информация',exact:true}).click();await expect(page.locator('.info-panel')).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(screenshots,'viewer.png')});await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Файлы',exact:true}).first().click();await page.locator('.folder-card').filter({hasText:'Photos'}).getByRole('button',{name:'Photos Папка на компьютере'}).click();await page.locator('.folder-card').filter({hasText:'Сочи 2014'}).getByRole('button',{name:'Сочи 2014 Папка на компьютере'}).click();await expect(page.getByRole('heading',{name:'Сочи 2014',exact:true})).toBeVisible();
await page.getByRole('button',{name:'Загрузить',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('input[type=file]:not([webkitdirectory])').setInputFiles(path.join(root,'artifacts/test-data/IMG_1201.jpg'));await expect(page.locator('.upload-panel')).toBeVisible();await expect(page.locator('.duplicate-actions')).toBeVisible({timeout:20000});await page.getByRole('button',{name:'Сохранить копию',exact:true}).click();await expect(page.getByText('Сохранён в Photos/Сочи 2014',{exact:true})).toBeVisible({timeout:20000});await page.getByRole('button',{name:'Свернуть загрузки'}).click();await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Альбомы',exact:true}).first().click();await expect(page.getByRole('button',{name:'Лето у моря 1 файлов'})).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(screenshots,'albums.png')});
await page.getByRole('button',{name:'Сменить тему'}).click();await page.getByRole('button',{name:/^Фото/}).first().click();await page.screenshot({animations:'disabled',path:path.join(screenshots,'desktop-dark.png')});
await page.getByRole('button',{name:'Хранилище',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Пространство для важного'})).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(screenshots,'storage-dark.png')});
for(const width of [375,390,430,768,1024,1440,1920]){
 await page.setViewportSize({width,height:900});await page.evaluate(()=>{document.querySelector('.nav')?.click()});if(width<=640)await page.locator('.bottom-nav').getByRole('button',{name:/^Фото/}).click();else await page.getByRole('button',{name:/^Фото/}).first().click();await page.waitForTimeout(250);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);if(overflow)failures.push('Overflow at '+width);
 await page.screenshot({animations:'disabled',path:path.join(screenshots,`photos-${width}.png`)});
}
await page.setViewportSize({width:390,height:844});await page.locator('.bottom-nav').getByRole('button',{name:'Загрузить или создать'}).click();await expect(page.getByRole('dialog',{name:'Добавить в LocalCloud'})).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(screenshots,'mobile-upload.png')});await page.getByRole('button',{name:'Закрыть',exact:true}).click();
await page.locator('.bottom-nav').getByRole('button',{name:'Ещё',exact:true}).click();await page.locator('.mobile-more').getByRole('button',{name:'Настройки',exact:true}).click();await expect(page.getByRole('heading',{name:'Настройки',exact:true})).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(screenshots,'mobile-settings.png')});
await page.reload();await expect(page.locator('.bottom-nav')).toBeVisible();
console.log(JSON.stringify({screenshots:screenshots,failures,consoleErrors},null,2));await browser.close();if(failures.length||consoleErrors.length)process.exit(1);
